vgames.df <- read.csv("E:\\vgsales.csv", sep = ";")
levels(vgames.df$Platform)
levels(vgames.df$Genre)
mytable <- xtabs(~ newvgames.df$Global_Sales + newvgames.df$Platform)
chisq.test(mytable)
mytable <- xtabs(~ newvgames.df$Global_Sales + newvgames.df$Genre)
chisq.test(mytable)
mytable <- xtabs(~ newvgames.df$Global_Sales + newvgames.df$Year_of_Release)
chisq.test(mytable)
mytable <- xtabs(~ newvgames.df$Global_Sales + newvgames.df$Publisher)
chisq.test(mytable)
columns = c("Global_Sales", "NA_Sales", "EU_Sales", "JP_Sales", "Other_Sales")
vgamesVariables <- newvgames.df[, columns]
res <- cor(vgamesVariables)
round(res, 2)
library(corrplot)
M <- cor(newvgames.df[, columns])
corrplot(M, method="circle")